### ISSUE TITLE
Issue installing with devtools

### ISSUE THREAD

**Issue by jbp7** [PMildenb/SteppedPower#3]
When I ran the installation commands, I get the following errors:

Error : (converted from warning) /private/var/folders/dz/m1k6bghs7xb3w34p0vkxs0_w0000gn/T/RtmpgSJXXl/R.INSTALL32911ff55e12/SteppedPower/man/compute_wlsPower.Rd:37: unknown macro '\cdot'
ERROR: installing Rd objects failed for package ‘SteppedPower’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SteppedPower’

Is there a reason for this?

**Comment by federicomarini** [comment]
Looks like it is simply converted from a warning, so not a proper error...

Try maybe with 

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```

before calling `install_github`

**Comment by jbp7** [comment]
Thanks! That seems to have resolved it.
